[workspace]
resolver = "2"
members = [ "microbenchmarks", "microbenchmarks-cli","uwgpu", "web-server"]

[workspace.dependencies]
wgpu = "22.1.0"
log = "0.4.22"
env_logger = "0.11.5"
bytemuck = "1.17.1"
thiserror = "1.0.64"
