[workspace]
resolver = "2"
members = [ "crates/*" ]

[workspace.dependencies]
wgpu = "23.0.0"
wgpu-async = "23.0.0"
log = "0.4.22"
env_logger = "0.11.5"
bytemuck = "1.17.1"
thiserror = "1.0.64"
wasm-bindgen = "=0.2.95"
