[package]
name = "microbenchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
uwgpu = { path = "../uwgpu" }
bytemuck = { workspace = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
rand = "0.8.5"
