[package]
name = "microbenchmarks-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
microbenchmarks = { path = "../microbenchmarks" }
clap = { version = "4.5", features = ["derive", "unstable-v5"] }
